config/routes.rb
Signature::Application.routes.draw do
  resources :user_signatures

end

app/models/user_signature.rb
class UserSignature < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_signatures_controller.rb
class UserSignaturesController < ApplicationController
  before_action :set_user_signature, only: [:show, :edit, :update, :destroy]

  # GET /user_signatures
  # GET /user_signatures.json
  def index
    @user_signatures = UserSignature.all
  end

  # GET /user_signatures/1
  # GET /user_signatures/1.json
  def show
  end

  # GET /user_signatures/new
  def new
    @user_signature = UserSignature.new
  end

  # GET /user_signatures/1/edit
  def edit
  end

  # POST /user_signatures
  # POST /user_signatures.json
  def create
    @user_signature = UserSignature.new(user_signature_params)

    respond_to do |format|
      if @user_signature.save
        format.html { redirect_to @user_signature, notice: 'User signature was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_signature }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_signatures/1
  # PATCH/PUT /user_signatures/1.json
  def update
    respond_to do |format|
      if @user_signature.update(user_signature_params)
        format.html { redirect_to @user_signature, notice: 'User signature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_signatures/1
  # DELETE /user_signatures/1.json
  def destroy
    @user_signature.destroy
    respond_to do |format|
      format.html { redirect_to user_signatures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_signature
      @user_signature = UserSignature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_signature_params
      params.require(:user_signature).permit(:name, :description, :signature)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_signatures_helper.rb
module UserSignaturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Signature</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_signatures/_form.html.erb
<%= form_for(@user_signature) do |f| %>
  <% if @user_signature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_signature.errors.count, "error") %> prohibited this user_signature from being saved:</h2>

      <ul>
      <% @user_signature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :signature %><br>
    <%= f.text_field :signature %>
  </div>
  <div style="max-width: 500px">
  <div id="signature">
    
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_signatures/edit.html.erb
<h1>Editing user_signature</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_signature %> |
<%= link_to 'Back', user_signatures_path %>

app/views/user_signatures/index.html.erb
<h1>Listing user_signatures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Signature</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_signatures.each do |user_signature| %>
      <tr>
        <td><%= user_signature.name %></td>
        <td><%= user_signature.description %></td>
        <td><%= user_signature.signature %></td>
        <td><%= link_to 'Show', user_signature %></td>
        <td><%= link_to 'Edit', edit_user_signature_path(user_signature) %></td>
        <td><%= link_to 'Destroy', user_signature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User signature', new_user_signature_path %>

app/views/user_signatures/new.html.erb
<h1>New user_signature</h1>

<%= render 'form' %>

<%= link_to 'Back', user_signatures_path %>

app/views/user_signatures/show.html.erb
<div class="bad">  
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @user_signature.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @user_signature.description %>
  </p>

  <p>
    <strong>Signature:</strong>
    <%= @user_signature.signature %>
  </p>
</div>
<div class="letterContainer">
  <div class="companyInfoContainer">
      <div class="companyInfoBox">
          <p><strong>Company Name <br> Company Address</strong> <br> Date of Letter</p>
      </div>
  </div>

  <div class="RecipientInfoBox">
      <p>Recipient's name <br> Recipient's title <br> Recipient's company <br> Recipient's company address
      <br><br>Recipient's Name:</p>
  </div>

  <div class="bodyParagraphContainer">
      <p>People read business letters quickly. Therefore, get to the point in the first paragraph--the first sentence, if possible. In other words, state what you want up front.</p>
      <p>Single space your letters and use a serif typeface. Skip a line between paragraphs. Because people read business letters quickly, use shorter sentences and paragraphs than you would in a longer document. Sentences should average fewer than twenty words, and paragraphs should average fewer than seven lines. </p>
      <p>Space your letter on the page so that it does not crowd the top. However, if possible, keep your letter to one page. Second pages often are not read. Send copies to anyone whose name you mention in the letter or who would be directly affected by the letter. </p>
      <p>Final paragraphs should tell readers what you want them to do or what you will do for them. </p>
  </div>
  <div class="signOffContainer">
      <div class="signOffBox">
          <p>Sincerely,
            <br><br>
            <div id='signature'></div>
            <br><br>
          </p>
      </div>
  </div>
  <p>Enclosure <br><br> cc: Name to receive copy</p>
</div>

<div class='links'>
  <%= link_to 'Edit', edit_user_signature_path(@user_signature) %> |
  <%= link_to 'Back', user_signatures_path %>
</div>